language: scala
jdk:
- oraclejdk8
scala:
- 2.11.11
- 2.12.4
script:
- sbt ++$TRAVIS_SCALA_VERSION test packageBin packageDoc packageSrc
deploy:
  provider: bintray
  file: .bintray.json
  user: digital-magic
  key:
    secure: VFnEo7/l0to3Lf/9JuNMwONgcQy2t5qHo06sSMmtVdD+9ZDGpFLtY6ocb5j6tT89JXNabsWSkYe1ibYRhaCMrTk7n43M4hQjurbi3hu0f+HaKAGMa6Cz95l8NeN6w91a/Qsv4/5KJ5zVvdXWiHW4jL0q1BoVkPZ5u/+wRrmFApeKMf18zjdCUZzzk3dE4kRjmvumRIg11rryW/k3GW7fSfvq1vJ6YxRZYbz6BAO45cKz3I/Mx6hZCu4RoRhffdD3qjvUQhXVe8L2MJWJUvtojaoTPQvC0rFpSKuokUYD1WEXOesKUb/EK5tGA9XjTOy64aIQHh8T4l0BH0E6FpJRmCW3djswN8VZfLY+ChFlU3QLUE+SDVlGinAhTiuWgSo5pXEIQ687VijdIe+jKTQLUGNVzRRua8tLyuN/MVhiRkVvzNWExcImorIQw/JFsLC+QSQ6bAGZO4yp2nZHVFw4+zeEipduIHN+2hBSFe1EWEhPAvIg20bhQENZmM8Vgn+L45CCzYiPdx1UW2z6T1LF+aftU+V9M2gm4Xt54rDEr5E/g++66Ej+cP5iRiQJspx7EWXFLwJKowTtoIjUB2ylmw5KJcN+AatZ+RUULf0r3QXEJN/w7Dd8zKssgCOYzXMr6y6n1celGF5DA41mJRlTYvqE9R3ZYpesbCTD82Nn0rI=
  dry-run: true
  on: master
